channels:
  - apple
  - conda-forge

dependencies:
  - python==3.8.12
  - dask==2021.11.2
  - tensorflow-deps==2.7.0
  - numpy>=1.19.2,<1.20.0
  - scipy>=1.7.3,<1.8.0
  - scikit-learn>=0.24,<0.25
  - matplotlib==3.5.1
  - pip
  - pip:
      - absl-py==0.13.0
      - aio-pika==6.8.2
      - aiofiles==0.8.0
      - aiohttp==3.7.4
      - aioredis==2.0.1
      - aioresponses==0.7.2
      - aiormq==3.3.1
      - anyio==3.4.0
      - APScheduler==3.7.0
      - astunparse==1.6.3
      - async-generator==1.10
      - async-timeout==3.0.1
      - attrs==21.2.0
      - bidict==0.22.0
      - httpcore==0.11.1
      - httplib2==0.20.2
      - httptools==0.4.0
      - httpx==0.15.4
      - blinker==1.4
      - boto3==1.21.26
      - botocore==1.24.26
      - cachecontrol==0.12.10
      - cached-property==1.5.2
      - cachetools==4.2.4
      - cachy==0.3.0
      - certifi==2021.10.8
      - cffi==1.15.0
      - chardet==3.0.4
      - clang==5.0
      - cleo==0.8.1
      - clikit==0.6.2
      - cloudpickle==1.6.0
      - colorama==0.4.4
      - colorclass==2.2.2
      - coloredlogs==15.0.1
      - colorhash==1.0.4
      - crashtest==0.3.1
      - croniter==1.1.0
      - cytoolz==0.11.2
      - cryptography==3.4.8
      - cycler==0.11.0
      - decorator==5.1.0
      - defusedxml==0.7.1
      - distlib==0.3.4
      - dm-tree==0.1.6
      - dnspython==1.16.0
      - docopt==0.6.2
      - fakeredis==1.7.0
      - fbmessenger==6.0.0
      - filelock==3.4.2
      - fire==0.4.0
      - flatbuffers==2.0
      - freezegun==1.1.0
      - fsspec==2022.2.0
      - future==0.18.2
      - gitdb==4.0.9
      - gast==0.4.0
      - GitPython==3.1.3
      - google-auth==2.3.3
      - google-pasta==0.2.0
      - greenlet==1.1.2
      - grpcio==1.45.0
      - h11==0.9.0
      - HeapDict==1.0.1
      - html5lib==1.1
      - humanfriendly==10.0
      - idna==3.3
      - importlib-metadata==4.11.3
      - ipaddress==1.0.23
      - isodate==0.6.1
      - jmespath==1.0.0
      - joblib==1.0.1
      - jsonpickle==2.0.0
      - jsonschema==3.2.0
      - kafka-python==2.0.2
      - keyring==21.8.0
      - keras-preprocessing==1.1.2
      - keras==2.7.0
      - kiwisolver==1.4.0
      - locket==0.2.1
      - lockfile==0.12.2
      - libclang==13.0.0
      - lxml==4.7.1
      - markdown==3.3.6
      - mattermostwrapper==2.2
      - matplotlib==3.3.4
      - mock==4.0.3
      - multidict==5.2.0
      - msgpack==1.0.3
      - munkres==1.1.4
      - mypy_extensions==0.4.3
      - networkx==2.6.3
      - oauth2client==4.1.3
      - oauthlib==3.2.0
      - onelogin==2.0.2
      - opt-einsum==3.3.0
      - packaging==20.9
      - pamqp==2.3.0
      - partd==1.2.0
      - pastel==0.2.1
      - pexpect==4.8.0
      - pika==1.2.0
      - pillow==9.0.1
      - pkgconfig==1.5.5
      - pkginfo==1.8.2
      - platformdirs==2.4.1
      - poetry==1.1.12
      - poetry-core==1.0.7
      - prompt-toolkit==2.0.10
      - prompt-toolkit==2.0.10
      - protobuf==3.19.4
      - psycopg2-binary==2.9.3
      - ptyprocess==0.7.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydot==1.4.2
      - pykwalify==1.8.0
      - pylev==1.4.0
      - pycparser==2.21
      - pyjwt==2.1.0
      - pyyaml==5.4.1
      - pymongo==3.10.1
      - pyrsistent==0.18.1
      - pyTelegramBotAPI==3.8.3
      - python-crfsuite==0.9.8
      - python-dateutil==2.8.2
      - python-engineio==4.3.1
      - python-socketio==5.5.2
      - python3-saml==1.12.0
      - pytz==2021.3
      - questionary==1.10.0
      - randomname==0.1.5
      - redis==3.5.3
      - regex==2021.8.28
      - rfc3986==1.5.0
      - rocketchat-API==1.16.0
      - rsa==4.8
      - ruamel.yaml==0.16.13
      - ruamel.yaml.clib==0.2.6
      - s3transfer==0.5.2
      - sanic==21.12.1
      - sanic-jwt==1.7.0
      - sanic-routing==0.7.2
      - sanic-cors==2.0.1
      - sentry-sdk==1.3.1
      - shellingham==1.4.0
      - simple-image-download==0.2
      - sklearn-crfsuite==0.3.6
      - slackclient==2.9.3
      - smmap==5.0.0
      - sniffio==1.2.0
      - SQLAlchemy==1.4.32
      - tabulate==0.8.9
      - tarsafe==0.0.3
      - tensorboard==2.7.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.7.0
      - tensorflow-hub==0.12.0
      - tensorflow-macos==2.7.0
      - tensorflow-metal==0.3.0
      - tensorflow-probability==0.13.0
      - termcolor==1.1.0
      - terminaltables==3.1.10
      - threadpoolctl==3.1.0
      - tfa-nightly==0.16.0.dev20220103155136
      - tomlkit==0.8.0
      - toolz==0.11.2
      - tqdm==4.63.1
      - twilio==6.50.1
      - typeguard==2.13.3
      - typing-extensions==3.10.0.2
      - typing-utils==0.1.0
      - tzlocal==2.1
      - ujson==4.3.0
      - uvloop==0.14.0
      - urllib3==1.26.9
      - virtualenv==20.13.0
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - webexteamssdk==1.6
      - websockets==10.2
      - werkzeug==2.0.3
      - wrapt==1.14.0
      - yarl==1.7.2
      - zict==2.0.0
      - zipp==3.7.0
      - requests-toolbelt==0.9.1
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==0.9.1